# Generated by Django 3.1.12 on 2021-07-18 17:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_auto_20210629_1520'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ('date',)},
        ),
    ]
