# Generated by Django 3.1.13 on 2021-09-14 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20210624_1742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='experience',
        ),
    ]
