# Generated by Django 3.1.13 on 2022-01-12 09:51

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_customuser_experience'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, default='profile1.png', max_length=255, null=True),
        ),
    ]
